version: "3.1"

services:
  main:
    hostname: nginx
    image: nginx:1.23.2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/certbot/www:/var/www/certbot/:ro
      - /home/ubuntu/certbot/conf/:/etc/nginx/ssl/:ro
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  certbot:
    hostname: certbot
    restart: unless-stopped
    image: certbot/certbot:latest
    volumes:
      - /home/ubuntu/certbot/www/:/var/www/certbot/:rw
      - /home/ubuntu/certbot/conf/:/etc/letsencrypt/:rw
