version: "3.1"

services:
  main:
    hostname: nginx
    image: nginx:1.23.2-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    logging:
      options:
        max-size: "10m"
        max-file: "3"
